spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false
    username: root
    password: mysqlGT#1092
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

